// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbUwy_lLjfTKa47IQ9ESDIciYJQm05iBs',
    appId: '1:40189270169:web:987274495a2840afc84008',
    messagingSenderId: '40189270169',
    projectId: 'mariam-6e152',
    authDomain: 'mariam-6e152.firebaseapp.com',
    storageBucket: 'mariam-6e152.appspot.com',
    measurementId: 'G-RGDX11PXVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdmPMh-p5b-wdrKleYgIbN0CtMpJ_O59Y',
    appId: '1:40189270169:android:54116130a201c468c84008',
    messagingSenderId: '40189270169',
    projectId: 'mariam-6e152',
    storageBucket: 'mariam-6e152.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTbkh-A-taBe4mbT521WdzwHBYhhdT6Vk',
    appId: '1:40189270169:ios:f09d97feb06a4ddcc84008',
    messagingSenderId: '40189270169',
    projectId: 'mariam-6e152',
    storageBucket: 'mariam-6e152.appspot.com',
    iosBundleId: 'com.example.storApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTbkh-A-taBe4mbT521WdzwHBYhhdT6Vk',
    appId: '1:40189270169:ios:f09d97feb06a4ddcc84008',
    messagingSenderId: '40189270169',
    projectId: 'mariam-6e152',
    storageBucket: 'mariam-6e152.appspot.com',
    iosBundleId: 'com.example.storApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbUwy_lLjfTKa47IQ9ESDIciYJQm05iBs',
    appId: '1:40189270169:web:995c1229501d0029c84008',
    messagingSenderId: '40189270169',
    projectId: 'mariam-6e152',
    authDomain: 'mariam-6e152.firebaseapp.com',
    storageBucket: 'mariam-6e152.appspot.com',
    measurementId: 'G-GPB5QJL2QX',
  );

}